version: '3.8'
services:
  nodeserver:
    build:
      context: .
    ports:
      - "8080:8080"
  nginx:
      build:
        context: ./nginx
      container_name: nginx
      ports:
        - "80:80"
